"""Add login_attempts and locked to UserModel

Revision ID: 29ad5ed19cb6
Revises: 33b936694a82
Create Date: 2025-06-12 18:15:10.954957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ad5ed19cb6'
down_revision = '33b936694a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('locked')
        batch_op.drop_column('login_attempts')

    # ### end Alembic commands ###
