"""Added columns name, price, quantity to ItemModel table

Revision ID: e68cf3827aec
Revises: 29ad5ed19cb6
Create Date: 2025-06-14 21:17:52.966205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68cf3827aec'
down_revision = '29ad5ed19cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_model', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
